# Generated by Django 5.1.6 on 2025-02-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_code', models.IntegerField(db_column='Client_code', primary_key=True, serialize=False)),
                ('familia', models.TextField(blank=True, db_column='Familia', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('otchestvo', models.TextField(blank=True, db_column='Otchestvo', null=True)),
                ('adress', models.TextField(blank=True, db_column='Adress', null=True)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_number', max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('presence_absence_of_a_car', models.IntegerField(blank=True, db_column='Presence_absence_of_a_car', null=True)),
                ('presence_absence_of_real_estate', models.IntegerField(blank=True, db_column='Presence_absence_of_real_estate', null=True)),
                ('month_income', models.IntegerField(blank=True, db_column='Month_income', null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['familia', 'name', 'otchestvo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('credit_code', models.IntegerField(db_column='Credit_code', primary_key=True, serialize=False)),
                ('credit_amount', models.DecimalField(blank=True, db_column='Credit_amount', decimal_places=2, max_digits=20, null=True)),
                ('term_month', models.IntegerField(blank=True, db_column='Term_month', null=True)),
                ('monthly_payment_amount', models.DecimalField(blank=True, db_column='Monthly_payment_amount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditStatement',
            fields=[
                ('loan_repayment_number', models.IntegerField(db_column='Loan_repayment_number', primary_key=True, serialize=False)),
                ('loan_issuance_date', models.DateField(blank=True, db_column='Loan_issuance_date', null=True)),
                ('loan_repayment_date', models.DateField(blank=True, db_column='Loan_Repayment_Date', null=True)),
                ('redemption_status', models.IntegerField(blank=True, db_column='Redemption_status', null=True)),
            ],
            options={
                'db_table': 'credit_statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('credit_type_code', models.IntegerField(db_column='Credit_type_code', primary_key=True, serialize=False)),
                ('credit_type_name', models.TextField(blank=True, db_column='Credit_type_name', null=True)),
                ('credit_percent', models.DecimalField(blank=True, db_column='Credit_percent', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'credit_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('deposit_code', models.IntegerField(db_column='Deposit_code', primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(blank=True, db_column='Deposit_amount', decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'deposits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTypes',
            fields=[
                ('deposit_type_code', models.IntegerField(db_column='Deposit_type_code', primary_key=True, serialize=False)),
                ('name_of_deposit_type', models.TextField(blank=True, db_column='Name_of_deposit_type', null=True)),
                ('deposit_percent', models.DecimalField(blank=True, db_column='Deposit_percent', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'deposit_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptiveStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(blank=True, db_column='Calculation_date', null=True)),
                ('average_value', models.DecimalField(blank=True, db_column='Average_value', decimal_places=2, max_digits=10, null=True)),
                ('total_sum', models.DecimalField(blank=True, db_column='Total_sum', decimal_places=2, max_digits=20, null=True)),
                ('maximum_value', models.DecimalField(blank=True, db_column='Maximum_value', decimal_places=2, max_digits=10, null=True)),
                ('minimum_value', models.DecimalField(blank=True, db_column='Minimum_value', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'descriptive_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatementOfDeposits',
            fields=[
                ('deposit_closing_number', models.IntegerField(db_column='Deposit_closing_number', primary_key=True, serialize=False)),
                ('deposit_opening_date', models.DateField(blank=True, db_column='Deposit_opening_date', null=True)),
                ('deposit_ending_date', models.DateField(blank=True, db_column='Deposit_ending_date', null=True)),
                ('deposit_closing_status', models.IntegerField(blank=True, db_column='Deposit_Closing_Status', null=True)),
            ],
            options={
                'db_table': 'statement_of_deposits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_deposits', models.IntegerField(blank=True, null=True)),
                ('closed_deposits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics',
                'managed': False,
            },
        ),
    ]
