# Generated by Django 5.1.6 on 2025-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('patronymic', models.TextField()),
                ('adress', models.TextField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.TextField(blank=True, null=True)),
                ('flag_own_car', models.IntegerField(blank=True, null=True)),
                ('flag_own_property', models.IntegerField(blank=True, null=True)),
                ('month_income', models.IntegerField()),
                ('count_children', models.IntegerField()),
                ('education_type', models.TextField(blank=True, null=True)),
                ('passport_serial_number', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditStatement',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('number_of_the_loan_agreement', models.IntegerField(unique=True)),
                ('credit_amount', models.IntegerField()),
                ('term_month', models.IntegerField()),
                ('monthly_payment', models.IntegerField()),
                ('loan_opening_date', models.DateField(blank=True, null=True)),
                ('repayment_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credit_statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanTypes',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('registration_number', models.IntegerField(unique=True)),
                ('name_of_the_type', models.TextField()),
                ('interest_rate', models.FloatField()),
            ],
            options={
                'db_table': 'loan_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_status', models.TextField()),
            ],
            options={
                'db_table': 'payroll',
                'managed': False,
            },
        ),
    ]
